---
abstract: 'stream long responses instead of sending them in one piece'
author:
  - 'Michael McClennen <mmcclenn@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-StreamData
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: '1.3'
version: '0.9'
